require:
  - rubocop-performance

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true